wheel_radius: 0.033     # The radius of the wheels
wheel_base: 0.16        # The distance between the wheels

# wheel_radius: 0.1     # The radius of the wheels
# wheel_base: 0.26      # The distance between the wheels
